openapi: 3.0.3
info:
  title: Clinical Research Services API
  version: 1.0.0
  description: REST API for managing clinical trials used by the evidence and care-plan agents.
servers:
  - url: http://localhost:8002
paths:
  /services:
    get:
      summary: Get service capabilities
      responses:
        '200':
          description: Service metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInfo'
  /trials:
    get:
      summary: List all trials
      responses:
        '200':
          description: Array of clinical trials
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trial'
    post:
      summary: Create a new clinical trial
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrialCreate'
      responses:
        '201':
          description: Trial created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trial'
  /trials/{trial_id}:
    get:
      summary: Retrieve a single trial
      parameters:
        - in: path
          name: trial_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Trial detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trial'
        '404':
          description: Trial not found
components:
  schemas:
    ServiceInfo:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        capabilities:
          type: array
          items:
            type: string
    Trial:
      type: object
      properties:
        id:
          type: integer
        nct_id:
          type: string
        title:
          type: string
        condition:
          type: string
        phase:
          type: string
        status:
          type: string
        principal_investigator:
          type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
          nullable: true
        site_distance_km:
          type: number
          format: float
          nullable: true
        eligibility_summary:
          type: string
          nullable: true
    TrialCreate:
      type: object
      properties:
        nct_id:
          type: string
          nullable: true
        title:
          type: string
        condition:
          type: string
        phase:
          type: string
        status:
          type: string
        principal_investigator:
          type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
          nullable: true
      required:
        - title
        - condition
        - phase
        - status
        - principal_investigator
        - start_date
