# Choreo Component Configuration for Trial Registry Backend Service
# +required Version of the configuration file
# +optional Display name for the component
# +optional Description about the component
# +required Type of the component (Service, Scheduled Task, Manual Task, Test Runner, Web Application)

apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  # +required Type of the component
  type: Service
  
  # +optional Display name of the component
  displayName: Trial Registry Backend Service
  
  # +optional Description of the component
  description: FastAPI service for managing clinical trial information, providing REST API for trial data used in healthcare research and patient matching workflows.
  
  # +optional Incoming connection details for the component (AKA endpoints)
  inbound:
    # +required Unique name for the endpoint
    - name: Trial Registry API
      # +required Numeric port value that the service is listening on
      port: 8002
      # +required Type of traffic that the endpoint is accepting
      # Allowed values: REST, GraphQL, GRPC, UDP, TCP
      type: REST
      # +optional Network visibility of the endpoint
      # Allowed values: Public, Organization, Project
      # Default: Public
      networkVisibility: Public
      # +optional Context (base path) of the endpoint
      context: /
      # +optional Path to the OpenAPI specification file (for REST endpoints)
      # schemaFilePath: openapi.yaml
  
  # +optional Build configuration for the component
  build:
    # +required Base image for building the component
    # Available base images:
    # - ballerina:2201.10.0, ballerina:2201.9.2, ballerina:2201.8.6
    # - nodejs:20-alpine, nodejs:18-alpine
    # - python:3.11, python:3.10, python:3.9, python:3.8
    # - php:8.3-apache, php:8.2-apache, php:8.1-apache
    # - wso2/choreo-connect-apk-adapter:1.2.0
    baseImage: python:3.11
    
    # +optional Build type
    # Allowed values: dockerfile, buildpacks
    buildType: buildpacks
    
    # +optional Path to the Python application entry point
    # For Uvicorn/FastAPI apps, this should point to the module:app
    # e.g., app:app means run "uvicorn app:app"
    
  # +optional Runtime environment configurations
  env:
    # +optional List of environment variables
    - name: TRIAL_REGISTRY_TITLE
      value: "Clinical Research Services API"
      isSecret: false
    - name: TRIAL_REGISTRY_DESCRIPTION
      value: "Minimal REST API for managing clinical trials"
      isSecret: false
    - name: TRIAL_REGISTRY_ALLOW_ORIGINS
      value: "*"
      isSecret: false
