openapi: 3.0.3
info:
  title: EHR Service API
  version: 1.0.0
  description: REST API exposing mock electronic health record capabilities.
servers:
  - url: http://localhost:8001
paths:
  /patients/{patient_id}/summary:
    get:
      summary: Retrieve patient summary
      parameters:
        - in: path
          name: patient_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Patient summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientSummary'
        '404':
          description: Patient not found
  /patients/{patient_id}/labs:
    get:
      summary: Retrieve lab history
      parameters:
        - in: path
          name: patient_id
          required: true
          schema:
            type: string
        - in: query
          name: names
          required: false
          schema:
            type: string
          description: Comma separated lab names to filter.
        - in: query
          name: last_n
          required: false
          schema:
            type: integer
            minimum: 1
          description: Limit to the most recent N results.
      responses:
        '200':
          description: Lab response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LabResponse'
        '404':
          description: Patient not found or no lab history
  /orders/medication:
    post:
      summary: Create draft medication order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MedicationOrder'
      responses:
        '201':
          description: Draft order acknowledgement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
components:
  schemas:
    PatientDemographics:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        gender:
          type: string
        mrn:
          type: string
    VitalSigns:
      type: object
      properties:
        systolic:
          type: integer
        diastolic:
          type: integer
        heart_rate:
          type: integer
        weight_kg:
          type: number
        updated_at:
          type: string
          format: date-time
    PatientSummary:
      type: object
      properties:
        demographics:
          $ref: '#/components/schemas/PatientDemographics'
        problems:
          type: array
          items:
            type: string
        medications:
          type: array
          items:
            type: string
        vitals:
          $ref: '#/components/schemas/VitalSigns'
        last_a1c:
          type: number
        last_egfr:
          type: number
    LabValue:
      type: object
      properties:
        name:
          type: string
        value:
          type: number
        unit:
          type: string
        collected_at:
          type: string
          format: date-time
    LabResponse:
      type: object
      properties:
        patient_id:
          type: string
        labs:
          type: array
          items:
            $ref: '#/components/schemas/LabValue'
    MedicationOrder:
      type: object
      properties:
        patient_id:
          type: string
        medication:
          type: string
        dose:
          type: string
        route:
          type: string
        frequency:
          type: string
        rationale:
          type: string
      required:
        - patient_id
        - medication
        - dose
        - route
        - frequency
    OrderResponse:
      type: object
      properties:
        order_id:
          type: string
        status:
          type: string
